# Refer to the Snapcraft documentation at https://snapcraft.io/docs
# for more information on how to create a snapcraft.yaml file.
# See 'snapcraft plugins' and 'snapcraft help <plugin>' for specific
# details on those plugins.
# https://snapcraft.io/docs/snapcraft-top-level-metadata

# you probably want to 'snapcraft register <name>'
name: slack-send

# Incorporate external metadata via the referenced parts
adopt-info: slack-send

# the base snap is the execution environment for this snap
base: core22

# just for humans, typically '1.2+git' or '1.3.2'
version: '1.1.1'

# 79 char long summary
summary: Command line tool to send messages to Slack channels

description: SlackSend is a CLI tool to send slack messages to your channels with no dependency.

# must be 'stable' to release into candidate/stable channels
grade: devel

# use 'strict' once you have the right plugs and slots
confinement: devmode

# list of build and run architectures (https://snapcraft.io/docs/architectures)
#architectures:
#  - build-on: arm64
#    run-on: [ arm64, amd64 ]

# A list of features that must be supported by the core in order for this snap to install. 
# For example to make the snap only installable on certain recent version of snapd(like 2.38) you can specify:
#assumes:
#  - snapd2.38

icon: slack.channel.png

epoch:

#  app | kernel | gadget | os | core | base
type: app

# human-readable title for this snap
title: SlackSend

issues: https://github.com/cavecafe/slack-send/issues
contact: thomas <cavecafe@gmail.com>
package-repositories:
- type: apt
  key-id: F3AB71A9B4E0130AD5A17B067EB6A2FAC336E133
  url: https://github.com/cavecafe/slack-send/
  suites: [stable, testing]
  components: [main]
  architectures: [amd64, arm64]

# Files to pass through to the snap from the build environment
#passthrough:

#donation: |
#  If you find this tool useful, please consider supporting the developer by donating to the project.
#  - [GitHub Sponsors]()
#  - [Patreon]()

# System usernames the snap may need access to
#system-usernames:
#  - daemon

# Hooks to run during snap operations
#hooks:
#  prepare-device: scripts/prepare
#  configure: scripts/configure
#  start: scripts/start
#  stop: scripts/stop

apps:
  slack-send:
    command: /usr/local/bin/slack-send

website: https://github.com/cavecafe/slack-send

# Ubuntu App store metadata
#ua-services:
#  - slack-send
#  - browser-services

# Layout of files in the snap
layout:
  /usr/local/slack-send/:
    bind: $SNAP/usr/local/slack-send/
  /usr/local/bin/slack-send:
    symlink: /usr/local/slack-send/slack-send

license: MIT

environment:
  DOTNET_ROOT: $SNAP/usr/share/dotnet

# Interfaces the snap requires
# slots: [home, network]

source-code: https://github.com/cavecafe/slack-send

build-packages:
- dotnet-sdk-8.0
plugs:
  home:
    interface: personal-files
    read:
    - $HOME/.slack-send
    write:
    - $HOME/.slack-send
  network:
    interface: network
    target: network

compression: lzo
build-base: core24

parts:
  # instead of all self-contained per platforms, 
  # Snapcraft's remote build infrastructure (snapcraft.io build servers) 
  # can be leveraged to build for other platforms.
  slack-send-linux-x64:
    plugin: dotnet
    source: .
    dotnet-build-configuration: Release
    dotnet-self-contained-runtime-identifier: linux-x64
    build-packages:
    - dotnet-sdk-8.0
    stage-packages:
    - libicu72

#  slack-send-osx-arm64:
#    plugin: dotnet
#    source: .
#    dotnet-build-configuration: Release
#    dotnet-self-contained-runtime-identifier: osx-arm64
#    build-packages:
#      - dotnet-sdk-8.0
#    stage-packages:
#      - libicu72
#
#  slack-send-osx-x64:
#    plugin: dotnet
#    source: .
#    dotnet-build-configuration: Release
#    dotnet-self-contained-runtime-identifier: osx-x64
#    build-packages:
#      - dotnet-sdk-8.0
#    stage-packages:
#      - libicu72
#  
#  slack-send-windows-arm64:
#    plugin: dotnet
#    source: .
#    dotnet-build-configuration: Release
#    dotnet-self-contained-runtime-identifier: windows-arm64
#    build-packages:
#      - dotnet-sdk-8.0
#    stage-packages:
#      - libicu72
#  
#  slack-send-windows-x64:
#    plugin: dotnet
#    source: .
#    dotnet-build-configuration: Release
#    dotnet-self-contained-runtime-identifier: windows-x64
#    build-packages:
#      - dotnet-sdk-8.0
#    stage-packages:
#      - libicu72
