name: slack-send
adopt-info: slack-send
base: core24
# version.sh will be used to get the version 
# to replace the version in the snapcraft.yaml
version: 1.1.3

summary: Command line tool to send messages to Slack channels
description: SlackSend is a CLI tool to send slack messages.
grade: stable
confinement: strict

apps:
  slack-send:
    command: slack-send
    plugs: [ home, network ]

# (TODO) Modify this with proper image
icon: slack-send.png
type: app
title: SlackSend
issues: https://github.com/cavecafe/slack-send/issues
contact: thomas <cavecafe@gmail.com>
website: https://github.com/cavecafe/slack-send
license: MIT
environment:
  DOTNET_ROOT: $SNAP/usr/share/dotnet
  CRAFT_ARCH_TARGET_BUILD_FOR: "amd64,arm64,armhf,riscv64"
source-code: https://github.com/cavecafe/slack-send
build-packages:
  - dotnet-sdk-8.0
plugs:
  home:
    interface: personal-files
    read:
      - $HOME/.slack-send
    write:
      - $HOME/.slack-send
compression: lzo
build-base: core24

# noinspection YAMLSchemaValidation
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  riscv64:
    build-on: [riscv64]
    build-for: [riscv64]
parts:
  slack-send-src:
    plugin: dotnet
    source: https://github.com/cavecafe/slack-send.git
    source-branch: main
    # source-tag: snap-store
    build-packages:
      - dotnet-sdk-8.0
      - liblttng-ust1
