name: slack-send
version: 1.1.5
adopt-info: slack-send
summary: Command line tool to send messages to Slack channels
description: SlackSend is a CLI tool to send slack messages.
grade: stable
confinement: strict

base: core22
compression: lzo
icon: slack-send.png
type: app
title: SlackSend
issues: https://github.com/cavecafe/slack-send/issues
contact: https://github.com/cavecafe
website: https://github.com/cavecafe/slack-send
license: MIT

apps:
  slack-send:
    command: slack-send
    plugs: [ home, network ]

architectures:
  - build-on: amd64
  - build-on: arm64

environment:
  DOTNET_ROOT: $SNAP/usr/share/dotnet
  #CRAFT_ARCH_TARGET_BUILD_FOR: "amd64,arm64,armhf,riscv64"
source-code: https://github.com/cavecafe/slack-send
build-packages:
  - dotnet-sdk-8.0
  - dotnet-runtime-8.0

parts:
  slack-send:
    source: https://github.com/cavecafe/slack-send.git
    source-type: git
    source-branch: main
    # source-tag: snap-store
    plugin: autotools
    build-packages:
      - dotnet-sdk-8.0
    stage-packages:
      - dotnet-runtime-8.0
    dotnet-build-configuration: Release
    build-environment:
      - DOTNET_ROOT: $SNAP/usr/share/dotnet
    build-snaps:
      - dotnet-sdk-8.0
    stage-snaps:
      - dotnet-runtime-8.0
      - slack-send

plugs:
  home:
    read:
      - $HOME/.slack-send
    write:
      - $HOME/.slack-send
    network:
      - network