name: slack-send
adopt-info: slack-send
base: core22
# version.sh will be used to get the version 
# to replace the version in the snapcraft.yaml
version: 1.1.4

summary: Command line tool to send messages to Slack channels
description: SlackSend is a CLI tool to send slack messages.
grade: stable
confinement: strict

apps:
  slack-send:
    command: slack-send
    plugs: [ home, network ]

icon: slack-send.png
type: app
title: SlackSend
issues: https://github.com/cavecafe/slack-send/issues
contact: https://github.com/cavecafe
website: https://github.com/cavecafe/slack-send
license: MIT
environment:
  DOTNET_ROOT: $SNAP/usr/share/dotnet
  #CRAFT_ARCH_TARGET_BUILD_FOR: "amd64,arm64,armhf,riscv64"
source-code: https://github.com/cavecafe/slack-send
build-packages: 
  - dotnet-sdk-8.0
plugs:
  home:
    interface: personal-files
    read:
      - $HOME/.slack-send
    write:
      - $HOME/.slack-send
compression: lzo
build-base: core22

# for core22
architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  slack-send-src:
    plugin: dotnet
    source: https://github.com/cavecafe/slack-send.git
    source-branch: main
    # source-tag: snap-store
    build-packages: 
      - dotnet-sdk-8.0
    stage-packages:
      - dotnet-runtime-8.0
